const hpMemList = [
    {map:"Echo Ridge",world:"Real World",location:"Examine cable box (Science Club Room)",item:"HP Memory 10"},
    {map:"Echo Ridge",world:"Real World",location:"Hide Seek's HELP (Echo Ridge)",item:"HP Memory 20"},
    {map:"Echo Ridge", world:"Real World", location:"Hamer Nayl's HELP (Echo Ridge)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"Real World", location:"Angel Wise's HELP (Science Club Room)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"Real World", location:"Raida Briz's HELP (Roof)", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"School Gate CC BMW", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Rocket CC 2 BMW", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"Wave World", location:"Noise Wave 1 (Northmost of Echo Ridge)", item: "HP Memory 10"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Echo Ridge EM-Rd(1000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Echo Ridge EM-Rd(2000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Echo Ridge EM-Rd(4000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Noise Wave 1 (Northwest of Echo Ridge)(3000ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Noise Wave 1 (Northwest of Echo Ridge)(4500ƶ)", item: "HP Memory 20"},
    {map:"Echo Ridge", world:"(SHOP)Wave World", location:"Noise Wave 1 (Northwest of Echo Ridge)(6000ƶ)", item: "HP Memory 20"},

    {map:"Spica Mall", world:"Real World", location:"Examine SPIMO poster next to the Wave Station (Spica Mall)", item: "HP Memory 10"},
    {map:"Spica Mall", world:"Real World", location:"Kaz Nova's HELP (Mall Event Area)", item: "HP Memory 10"},
    {map:"Spica Mall", world:"Wave World", location:"Spica Mall BMW", item: "HP Memory 10"},
    {map:"Spica Mall", world:"Wave World", location:"Gum Machine CC BMW", item: "HP Memory 20"},

    {map:"WBG Studios", world:"Real World", location:"Sanc Quatr's HELP (Event Stage)", item: "HP Memory 10"},
    {map:"WBG Studios", world:"Wave World", location:"Event Stage CC 3 BMW", item: "HP Memory 20"},
    {map:"WBG Studios", world:"Wave World", location:"WBG Logo Noise BMW", item: "HP Memory 10"},
    {map:"WBG Studios", world:"(SHOP)Wave World", location:"WBG Main Building(2000ƶ)", item: "HP Memory 20"},
    {map:"WBG Studios", world:"(SHOP)Wave World", location:"WBG Main Building(3000ƶ)", item: "HP Memory 20"},
    {map:"WBG Studios", world:"(SHOP)Wave World", location:"WBG Main Building(5000ƶ)", item: "HP Memory 20"},

    {map:"Alohaha", world:"Real World", location:"Examine outfits display (Alohaha Castle)", item: "HP Memory 10"},
    {map:"Alohaha", world:"Real World", location:"Examine dragon statue (Beach)", item: "HP Memory 10"},
    {map:"Alohaha", world:"Wave World", location:"Alohaha Castle BMW", item: "HP Memory 20"},
    {map:"Alohaha", world:"Wave World", location:"Food Stand CC BMW", item: "HP Memory 10"},
    {map:"Alohaha", world:"Wave World", location:"Dragon Statue CC BMW", item: "HP Memory 20"},
    {map:"Alohaha", world:"Wave World", location:"Environment System 1 BMW", item: "HP Memory 10"},
    {map:"Alohaha", world:"Wave World", location:"Environment System 2 BMW", item: "HP Memory 20"},

    {map:"National WAZA HQ", world:"Real World", location:"Examine blue stairs (Satella Police HQ)", item: "HP Memory 10"},
    {map:"National WAZA HQ", world:"Real World", location:"Examine globe (Command Center)", item: "HP Memory 10"},
    {map:"National WAZA HQ", world:"Real World", location:"Examine computers next to Main Computer (Command Center)", item: "HP Memory 10"},
    {map:"National WAZA HQ", world:"Real World", location:"Vidy Otaku's HELP (Satella Police HQ)", item: "HP Memory 20"},
    {map:"National WAZA HQ", world:"Real World", location:"Rob Sidkic's HELP (Satella Police HQ)", item: "HP Memory 10"},
    {map:"National WAZA HQ", world:"Wave World", location:"Mowai Comp BMWHidden warp in corner of briefing room (Satella Police HQ)", item: "HP Memory 20"},
    {map:"National WAZA HQ", world:"Wave World", location:"Main Computer CC BMW", item: "HP Memory 10"},

    {map:"Dealer Hideout", world:"Real World", location:"Examine green machines (Secret Shelter)", item: "HP Memory 10"},
    {map:"Dealer Hideout", world:"Real World", location:"Examine first machine (Crimson Factory)", item: "HP Memory 10"},
    {map:"Dealer Hideout", world:"Real World", location:"Examine King's roulette (Dealer Base)", item: "HP Memory 10"},
    {map:"Dealer Hideout", world:"Wave World", location:"Air Duct CC BMW", item: "HP Memory 10"},
    {map:"Dealer Hideout", world:"Wave World", location:"Crimson Tank CC BMW", item: "HP Memory 10"},
    {map:"Dealer Hideout", world:"Wave World", location:"Crimson Machine 3 BMW", item: "HP Memory 20"},
    
    {map:"Orbital Base", world:"Real World", location:"Examine small monitors", item: "HP Memory 10"},
    {map:"Orbital Base", world:"Wave World", location:"Port Noise BMW (located opposite of green arrow)", item: "HP Memory 20"},
    {map:"Orbital Base", world:"(SHOP)Wave World", location:"Orbital Base(4000ƶ)", item: "HP Memory 20"},
    {map:"Orbital Base", world:"(SHOP)Wave World", location:"Orbital Base(6000ƶ)", item: "HP Memory 20"},
    {map:"Orbital Base", world:"(SHOP)Wave World", location:"Orbital Base(8000ƶ)", item: "HP Memory 20"},

    {map:"Meteor G Server", world:"Wave World", location:"Noise Wave 3 BMW (Giant Wave Station)", item: "HP Memory 10"},
    {map:"Meteor G Server", world:"Wave World", location:"Meteor Server 2 BMW", item: "HP Memory 20"},

    {map:"National Astro Wave", world:"Wave World", location:"National Astro Wave 1 BMW", item: "HP Memory 10"},

    {map:"Post-Game Areas", world:"Wave World", location:"Noise Wave 5 BMW", item: "HP Memory 10"},
    {map:"Post-Game Areas", world:"Wave World", location:"Outer Astro Wave 1 BMW", item: "HP Memory 20"},
    {map:"Post-Game Areas", world:"Wave World", location:"Planet FM Astro Wave 3 (20 Mega cards door)", item: "HP Memory 10"},
    {map:"Post-Game Areas", world:"Wave World", location:"Black Hole Server 1 BMW", item: "HP Memory 10"},
    {map:"Post-Game Areas", world:"Wave World", location:"Black Hole Server 2 BMW (past all Standard card door)", item: "HP Memory 20"},
    {map:"Post-Game Areas", world:"(SHOP)Wave World", location:"Outer Astro Wave 2(5000ƶ)", item: "HP Memory 20"},
    {map:"Post-Game Areas", world:"(SHOP)Wave World", location:"Outer Astro Wave 2(7500ƶ)", item: "HP Memory 20"},
    {map:"Post-Game Areas", world:"(SHOP)Wave World", location:"Outer Astro Wave 2(10000ƶ)", item: "HP Memory 20"},
]
